logging:
  level:
    root: info
spring:
  jpa:
    show-sql: true
  h2:
    console:
      path: /h2
#  datasource:
#    generate-unique-name: false
#    name: "web-expenses-db"
#    url: jdbc:h2:file:./h2/testdb
#    username: admin
#    password: admin

