logging:
  level:
    root: info
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    generate-unique-name: false
    name: "web-expenses-db"

